name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Some one will be assigned to this issue'' New issue'
        pr-message: 'Welcome and thank you for submiting this PR, One of the maintainers will review this before merge, ... notification is sent '' Pull request'
